### ISSUE TITLE
Project Outline Feedback

### ISSUE THREAD

**Issue by dan-hart** [james636/liftoff-assignments#1]
Overall looks interesting, what is your MVP here? I would try to narrow the scope of this project to a simpler idea. Think about the target audience, perhaps you could leave the blog/reviews and add/edit products in the backlog. There is a lot of new technologies/things you need to learn here. Shopping card, AuthoIO, GraphQL, and generating PDFs server-side is a lot for one developer to accomplish in 8 weeks. I would try to pick one or two new technologies to focus on to realistically accomplish this project in 8 weeks.

**Comment by dan-hart** [comment]
@james636 Also, please add a link to your project tracker to your outline. Thanks!

**Comment by james636** [comment]
For my first sprint I will include the home page, the login page and a cart page.  The Login will require address, email and possibly a username, but might just end up being the email account.  
The link for the project is: https://www.pivotaltracker.com/n/projects/2239228
